[package]
name = "rust_samples"
version = "0.1.0"
authors = ["Marat Solncev <marat.solncev@piano.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
